### ISSUE TITLE
Error with no friendly info.

### ISSUE THREAD

**Issue by brizer** [Linjovi/yoso#11]
The first time someone download the tool, execute `yoso init` directly. Since the template repository address is not configured, it will be abnormal.

![image](https://user-images.githubusercontent.com/12656301/68840555-ec597680-06fd-11ea-9532-1dc211d43f90.png)

It is recommended to promptly prompt the user to set the configuration item first.

**Comment by Linjovi** [comment]
The problem was caused by a previous break commit to change the configuration file. Remove the .yoso folder can solve it.

**Comment by brizer** [comment]
Where is `.yoso` file location?

**Comment by Linjovi** [comment]
In your user home directory.

**Comment by brizer** [comment]
Thanks.
